modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/DaBomb/issues"
license="MIT"

[[mods]]
modId="dabomb"
version="${file.jarVersion}"
displayName="Da Bomb"
displayURL="https://www.curseforge.com/minecraft/mc-mods/da-bomb"
authors="Mrbysco"
description='''
This mod will blow your mind (and caves) (and house)
'''
credits="Darkosto for the sounds / idea"

[[dependencies.dabomb]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.dabomb]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"