modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/DaBomb/issues"
license="MIT"

[[mods]]
modId="dabomb"
version="${file.jarVersion}"
displayName="Da Bomb"
displayURL="https://www.curseforge.com/minecraft/mc-mods/da-bomb"
authors="Mrbysco"
description='''
This mod will blow your mind (and caves) (and house)
'''
credits="Darkosto for the sounds / idea"

[[dependencies.dabomb]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.dabomb]]
modId="neoforge"
type="required"
versionRange="[21.11.0-beta,)"
ordering="NONE"
side="BOTH"